; ##################################################################################
; # This #Include file was generated by Image2Include.ahk, you must not change it! #
; ##################################################################################
Create_quickMatchButton2_bmp(NewHandle := False) {
Static hBitmap := 0
If (NewHandle)
   hBitmap := 0
If (hBitmap)
   Return hBitmap
VarSetCapacity(B64, 1128 << !!A_IsUnicode)
B64 := "Qk1OAwAAAAAAADYAAAAoAAAAFwAAAAsAAAABABgAAAAAABgDAAAAAAAAAAAAAAAAAAAAAAAAbGxsbGxsbGxsZWVlT09PeHh4wMDA8vLy/////Pz8+vr6/Pz8////////////////////x8fHe3t7SkpKWlpaa2trbGxsAAAAZmZmYmJid3d34+Pj////////////////////////////////////////////////////////////////7u7uiYmJVlZWAAAAkZGR/v7+/////////////////////////////////////////////////////////////////////////////v7+/v7+AAAA////////////////////////////////9/f39/f3////////////////////////////////////////////////////AAAA////////////////9vb20tLSq6urq6urrKystLS0////////////////////////0dHRr6+vuLi46+vr////////////AAAA////////3t7eqqqqqqqqqqqqq6urq6urq6urrKys1tbW////////////////////////r6+vqqqqqqqqqqqqw8PD////AAAA7u7urq6uqqqqqqqqqqqqqqqqq6urq6urq6urrKysubm5////////////////////////6+vrqqqqqqqqqqqqqampqampAAAAqqqqqqqqq6urq6urq6urq6urq6urq6urq6urqqqqqqqq/v7+////////////////////////5OTkq6urqqqqqqqqq6urAAAAqqqqqqqqq6urq6urq6urq6urq6urq6urq6urqqqq3d3d/v7+////////////////////////////9fX1q6urqqqqq6urAAAAq6urq6urq6urq6urq6urq6urq6urqqqqqqqq6+vr////////////////////////////////////////5OTkq6urq6urAAAAq6urq6urq6urq6urq6urq6urq6urqqqq6+vr////////////////////////////////////////////////xMTEq6urAAAA"
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", 0, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
VarSetCapacity(Dec, DecLen, 0)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", &Dec, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
; Bitmap creation adopted from "How to convert Image data (JPEG/PNG/GIF) to hBITMAP?" by SKAN
; -> http://www.autohotkey.com/board/topic/21213-how-to-convert-image-data-jpegpnggif-to-hbitmap/?p=139257
hData := DllCall("Kernel32.dll\GlobalAlloc", "UInt", 2, "UPtr", DecLen, "UPtr")
pData := DllCall("Kernel32.dll\GlobalLock", "Ptr", hData, "UPtr")
DllCall("Kernel32.dll\RtlMoveMemory", "Ptr", pData, "Ptr", &Dec, "UPtr", DecLen)
DllCall("Kernel32.dll\GlobalUnlock", "Ptr", hData)
DllCall("Ole32.dll\CreateStreamOnHGlobal", "Ptr", hData, "Int", True, "PtrP", pStream)
hGdip := DllCall("Kernel32.dll\LoadLibrary", "Str", "Gdiplus.dll", "UPtr")
VarSetCapacity(SI, 16, 0), NumPut(1, SI, 0, "UChar")
DllCall("Gdiplus.dll\GdiplusStartup", "PtrP", pToken, "Ptr", &SI, "Ptr", 0)
DllCall("Gdiplus.dll\GdipCreateBitmapFromStream",  "Ptr", pStream, "PtrP", pBitmap)
DllCall("Gdiplus.dll\GdipCreateHBITMAPFromBitmap", "Ptr", pBitmap, "PtrP", hBitmap, "UInt", 0)
DllCall("Gdiplus.dll\GdipDisposeImage", "Ptr", pBitmap)
DllCall("Gdiplus.dll\GdiplusShutdown", "Ptr", pToken)
DllCall("Kernel32.dll\FreeLibrary", "Ptr", hGdip)
DllCall(NumGet(NumGet(pStream + 0, 0, "UPtr") + (A_PtrSize * 2), 0, "UPtr"), "Ptr", pStream)
Return hBitmap
}