; ##################################################################################
; # This #Include file was generated by Image2Include.ahk, you must not change it! #
; ##################################################################################
Create_criticalUpgradeButton1_bmp(NewHandle := False) {
Static hBitmap := 0
If (NewHandle)
   hBitmap := 0
If (hBitmap)
   Return hBitmap
VarSetCapacity(B64, 1320 << !!A_IsUnicode)
B64 := "Qk3eAwAAAAAAADYAAAAoAAAAEQAAABIAAAABABgAAAAAAKgDAAAAAAAAAAAAAAAAAAAAAAAAESv/don/w9L/7fL+9fr/9vz/9///7e38zdb/x8//x8//X2JlIyMBmboAlcUAi74AiLsAACxO/6i8/77O/M/Y79rj+erx//////7+/ujs+8fP/2ltdykpEZm7AJm7AO78BPP/BfD/AgBqhP+7zP+9zf/I0P/I0P/N1//h6/zz+P/k6fywt94iIhGKsADp9gT5/wL79AH76gD97AAArrn2zdP/ytH/yND/yND/yNH+ydb+y9j/ytb/OToye50I5fQJ9f4G/eUA/+sD/+0G/OsOAN3d/tjY/9PU/8jQ/8jQ/8jQ/8fR/8fR/8fR/yIiCrnZFfX7CvrpBv/vE//uFv/uGebXEwD39/3y8vzd3vTJ0f/I0P/I0P/H0f/H0f9+hJY1NRP8/AL69QT97xXSxRuglg7TxyKgmSkA////////7vD7y9n9x9X7x9T8x9H/x9H/Q0VBdH4G9f0G9uYmX18bZ3U7wMKUcHBEW1sXAP////////7+/uTt/MfY+sbW+sfR/8fR/z5AOoGLBvn+Csy7H3BwRP///1lZJP///4ODVQD////////////9/f3j7f3G1vrH0f/H0f8+QDqBiwb5/gre0TBaWhaVlX3v7+j///9ubkAA/////////////////f393uT80dr5y9T9cXWCXl4G+/8M18sfbn1P////iIhVrq6PTloiAP////////////////////n7/93m+s3V/MTM9SIiEfr6BujjH1RlIfr6+vDw8Ofn51VmIgD////////////////////+///p8PzR2f3M1f4oKBjN0BHy8xCusjBfXx5ZYB5YYB68tDYA////////////////////////+/3/6Pb/zNr/jZeqLi4F8vkE/ewQ/+4R/+4g/+4i/OsfAP///////////////////////////////+Tz/8fW/ktPTkJCC+7uAP3zA/zsBP3tBf/rBwD////+/v7+/v79/f39/f37/f32/v/2/v/w+P/U3P3J0fo0NionKQz1/ynv/wbu/wDz9gYA7PL/6/L/4ef+3eT+3eT+2+P+0uD/0t//0d3/zdf/ydT+yNT+iZKmIiIRW2oPobIE6u0BAM/Y+s/Y+s7X+8zU/czU/cvV/crX/8rX/8rW/8nV/8jV/8fV/8fV/8fV/6Cqxl1iZSwtHgDE1P3E1P3F1P3M1P3M1P3L1P3I1f/I1P/I1P/I1f/G1f/G1f/H1f/H1f/H1f/H1P/H1P8A"
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", 0, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
VarSetCapacity(Dec, DecLen, 0)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", &Dec, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
; Bitmap creation adopted from "How to convert Image data (JPEG/PNG/GIF) to hBITMAP?" by SKAN
; -> http://www.autohotkey.com/board/topic/21213-how-to-convert-image-data-jpegpnggif-to-hbitmap/?p=139257
hData := DllCall("Kernel32.dll\GlobalAlloc", "UInt", 2, "UPtr", DecLen, "UPtr")
pData := DllCall("Kernel32.dll\GlobalLock", "Ptr", hData, "UPtr")
DllCall("Kernel32.dll\RtlMoveMemory", "Ptr", pData, "Ptr", &Dec, "UPtr", DecLen)
DllCall("Kernel32.dll\GlobalUnlock", "Ptr", hData)
DllCall("Ole32.dll\CreateStreamOnHGlobal", "Ptr", hData, "Int", True, "PtrP", pStream)
hGdip := DllCall("Kernel32.dll\LoadLibrary", "Str", "Gdiplus.dll", "UPtr")
VarSetCapacity(SI, 16, 0), NumPut(1, SI, 0, "UChar")
DllCall("Gdiplus.dll\GdiplusStartup", "PtrP", pToken, "Ptr", &SI, "Ptr", 0)
DllCall("Gdiplus.dll\GdipCreateBitmapFromStream",  "Ptr", pStream, "PtrP", pBitmap)
DllCall("Gdiplus.dll\GdipCreateHBITMAPFromBitmap", "Ptr", pBitmap, "PtrP", hBitmap, "UInt", 0)
DllCall("Gdiplus.dll\GdipDisposeImage", "Ptr", pBitmap)
DllCall("Gdiplus.dll\GdiplusShutdown", "Ptr", pToken)
DllCall("Kernel32.dll\FreeLibrary", "Ptr", hGdip)
DllCall(NumGet(NumGet(pStream + 0, 0, "UPtr") + (A_PtrSize * 2), 0, "UPtr"), "Ptr", pStream)
Return hBitmap
}