; ##################################################################################
; # This #Include file was generated by Image2Include.ahk, you must not change it! #
; ##################################################################################
Create_quickMatchButton1_bmp(NewHandle := False) {
Static hBitmap := 0
If (NewHandle)
   hBitmap := 0
If (hBitmap)
   Return hBitmap
VarSetCapacity(B64, 1832 << !!A_IsUnicode)
B64 := "Qk1eBQAAAAAAADYAAAAoAAAAKAAAAAsAAAABABgAAAAAACgFAAAAAAAAAAAAAAAAAAAAAAAAAAAAk5OT////////ycnJEhISAwMDr6+v////////ra2tPDw8zs7O////////////////////////////gYGBAAAAfT8A/4EA/4EAu18AFAoAKioq4ODg/////////////v7+RkZGAAAAk0oAjUcAAAAAfHx8////AAAAk5OT////////ycnJEhISAwMDr6+v////////ra2tPDw8zs7O////////////////////////////gYGBAAAAfT8A/4EA/4EA53UASyYAAAAAoaGh////////////t7e3AAAAQyIA4HEAtFsAAAAAfHx8////AAAAk5OT////////ycnJEhISAwMDr6+v////////ra2tPDw8zs7O////////2NjYr6+v////////////gYGBAAAAfT8ApVMAgEEAfT8AXS8AAAAAfHx8////////////kZGRAAAASyYAfT8ATicAAAAAfHx8////AAAAk5OT////////ycnJEhISAwMDr6+v////////ra2tPDw8zs7O////////jo6OTExM4ODg////////gYGBAAAAQCAAAAAAAAAAAAAAAAAAAAAAcnJy////////////gYGBAAAAAAAAAAAAAAAAAAAAfHx8////AAAAk5OT////////ycnJFhYWCAgIsLCw////////ra2tPDw8zs7O////////jo6OV1dX4+Pj////////gYGBAAAAGg0ABwcHdXV1jIyMiYmJiYmJvLy8////////////w8PDiYmJiYmJjIyMcnJyQEBAfHx8////AAAAk5OT////////1NTUT09PSkpKwMDA////////ra2tPDw8zs7O////////jo6OV1dX4+Pj////////gYGBAAAAFAoAHBwc1NTU////////////////////////////////////////////09PTVVVVfHx8////AAAAk5OT////////////////////////////////ra2tPDw8zs7O////////jo6OV1dX4+Pj////////gYGBAAAAFQsAGBgYwMDA////////////////////////////////////////////vb29T09PfHx8////AAAAkJCQ////////////////////////////////p6enOzs7zs7O////////jo6OV1dX4+Pj////////gYGBAAAAJBIAAAAAS0tLaWlpaWlpbGxsnZ2d////////////pqambm5uaWlpaWlpSUlJKCgofHx8////AAAATExMpqampqampqampqampqampqampqampqamXV1dMzMzzs7O////////jo6OV1dX4+Pj////////gYGBAAAAUioARSMAAAAAAAAAAAAAAAAAXV1d////////////ampqAAAAAAAAAAAAAAAAAAAAfHx8////Oh0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQv7+/////////hoaGUlJS4uLi////////g4ODAAAAfT8A+X4AvWAAnU8Aez4AAAAATExM6+vr////8fHxWVlZAAAAcTkAkkoAViwAAAAAe3t7////3nAAvWAAXjAAXjAAXjAAXjAAXjAAXjAAXjAAXjAAUyoAAAAAZWVlkJCQj4+PNTU1MjIyrKys0dHR1tbWZGRkAAAAu18A/4EA/4EA/4EA02sALBYAAAAAV1dXbm5uX19fBwcHIhEA0WoA/4EAuF0AAAAAQkJCurq6"
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", 0, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
VarSetCapacity(Dec, DecLen, 0)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", &Dec, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
; Bitmap creation adopted from "How to convert Image data (JPEG/PNG/GIF) to hBITMAP?" by SKAN
; -> http://www.autohotkey.com/board/topic/21213-how-to-convert-image-data-jpegpnggif-to-hbitmap/?p=139257
hData := DllCall("Kernel32.dll\GlobalAlloc", "UInt", 2, "UPtr", DecLen, "UPtr")
pData := DllCall("Kernel32.dll\GlobalLock", "Ptr", hData, "UPtr")
DllCall("Kernel32.dll\RtlMoveMemory", "Ptr", pData, "Ptr", &Dec, "UPtr", DecLen)
DllCall("Kernel32.dll\GlobalUnlock", "Ptr", hData)
DllCall("Ole32.dll\CreateStreamOnHGlobal", "Ptr", hData, "Int", True, "PtrP", pStream)
hGdip := DllCall("Kernel32.dll\LoadLibrary", "Str", "Gdiplus.dll", "UPtr")
VarSetCapacity(SI, 16, 0), NumPut(1, SI, 0, "UChar")
DllCall("Gdiplus.dll\GdiplusStartup", "PtrP", pToken, "Ptr", &SI, "Ptr", 0)
DllCall("Gdiplus.dll\GdipCreateBitmapFromStream",  "Ptr", pStream, "PtrP", pBitmap)
DllCall("Gdiplus.dll\GdipCreateHBITMAPFromBitmap", "Ptr", pBitmap, "PtrP", hBitmap, "UInt", 0)
DllCall("Gdiplus.dll\GdipDisposeImage", "Ptr", pBitmap)
DllCall("Gdiplus.dll\GdiplusShutdown", "Ptr", pToken)
DllCall("Kernel32.dll\FreeLibrary", "Ptr", hGdip)
DllCall(NumGet(NumGet(pStream + 0, 0, "UPtr") + (A_PtrSize * 2), 0, "UPtr"), "Ptr", pStream)
Return hBitmap
}