; ##################################################################################
; # This #Include file was generated by Image2Include.ahk, you must not change it! #
; ##################################################################################
Create_reverseUpgradeButton1_bmp(NewHandle := False) {
Static hBitmap := 0
If (NewHandle)
   hBitmap := 0
If (hBitmap)
   Return hBitmap
VarSetCapacity(B64, 1252 << !!A_IsUnicode)
B64 := "Qk2qAwAAAAAAADYAAAAoAAAAEQAAABEAAAABABgAAAAAAHQDAAAAAAAAAAAAAAAAAAAAAAAA/0XT/6T1/3fd+oLe+I7h/43o95bj/sz9//////f/9+T0Z2FaIiIROT4LgLMBgLMBc4kkAP976f973/933fR81/mR5P+O6feX5Pio7Pz1/P/1/yMjAUJVAJm7AJTHAIi7AIi7AIi7AAD8m/D+cuP6Ytj4Ytf9buH6kuj4kuf2kuX+0/wjIg92iwuZuwDi9QDy/gTw/wLw/wLu/wAA/6L3/nzn+WHY+mjb/XXj+ZPo+ZPo/ZjtLCgYYHUHm84I+/8B//wF++sC/OsA/u0A/OsAAPmX7Pya7/2H6f6T7v2a7/2a7/6c8eqQ2yIiEbTIA/T/BvzwBf3mAP/sBPnoC//uEf/wEwD0ruP/4/z/4Pv/se7/qe7/qe75reg8NSZriwDw+g788gr97A3/7xP/7hj45yBmZiJVXxgA+dr5/ez9//D9/7nw/6ru/L3x+uL2IyMBqdwQ+/sC/u0Q4tUer6gis6YR3s0nZmYi////APna+f3s/f/4//vg+P7c+Pzz/P/9/yAgD+T1GP7sEI+PGVxkJqWzebKyhl5eGltbF/n5+QD+7P799f3/5v/96f386/z97P3/+f8gIA/v/xL75hpZWSb///+qqoO1tZD09PJeXhr5+fkA//H//fb9/9/4/dz5/dz9/eD9//n/ICAP7/8S++YaaGgkaGgo2dnH+vr67e3rXl4a////AP/x//32/f/f+P7e+v/g//7j/v/5/yAgD+TkGP/sGWxsF/b48re3p3x8TYiUXE5aIvn5+QD/9v//9P/56Pn53fn+s/T72Pr/9P8xMSG7zAD9/QmDcguwt5r29vb39/eTmlZVZiL///8A//b//fD9/NP1/bPv+aXp/733//T/39/cISEP8voB5dQob3AdX18eWGAefoYhe4QjZmYiAP3u/fnI7vq36vms6Pmk6Pq07/3w/f///yAgDLK8Dv7uEf7tEP/uEf/uIvzrH/zrH//uIgD/5//+ufH/qu79qOz8p+v8p+v+xvX//f////8gIA/PzwHw+AL77QD87AX/6wj/6wb/6wkA//D/+On4/6ru/ajs/Kfr/Kjs/r7u//z+/////Pz8Hx8OmaoB9f8p7v8A9PwN8vIA//8AAP/w///7//XL7/2o7P6r7/3R7P/o9//+//////////T09DAwICorEGp8D8jQAvPzAcfWAwA="
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", 0, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
VarSetCapacity(Dec, DecLen, 0)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", &Dec, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
; Bitmap creation adopted from "How to convert Image data (JPEG/PNG/GIF) to hBITMAP?" by SKAN
; -> http://www.autohotkey.com/board/topic/21213-how-to-convert-image-data-jpegpnggif-to-hbitmap/?p=139257
hData := DllCall("Kernel32.dll\GlobalAlloc", "UInt", 2, "UPtr", DecLen, "UPtr")
pData := DllCall("Kernel32.dll\GlobalLock", "Ptr", hData, "UPtr")
DllCall("Kernel32.dll\RtlMoveMemory", "Ptr", pData, "Ptr", &Dec, "UPtr", DecLen)
DllCall("Kernel32.dll\GlobalUnlock", "Ptr", hData)
DllCall("Ole32.dll\CreateStreamOnHGlobal", "Ptr", hData, "Int", True, "PtrP", pStream)
hGdip := DllCall("Kernel32.dll\LoadLibrary", "Str", "Gdiplus.dll", "UPtr")
VarSetCapacity(SI, 16, 0), NumPut(1, SI, 0, "UChar")
DllCall("Gdiplus.dll\GdiplusStartup", "PtrP", pToken, "Ptr", &SI, "Ptr", 0)
DllCall("Gdiplus.dll\GdipCreateBitmapFromStream",  "Ptr", pStream, "PtrP", pBitmap)
DllCall("Gdiplus.dll\GdipCreateHBITMAPFromBitmap", "Ptr", pBitmap, "PtrP", hBitmap, "UInt", 0)
DllCall("Gdiplus.dll\GdipDisposeImage", "Ptr", pBitmap)
DllCall("Gdiplus.dll\GdiplusShutdown", "Ptr", pToken)
DllCall("Kernel32.dll\FreeLibrary", "Ptr", hGdip)
DllCall(NumGet(NumGet(pStream + 0, 0, "UPtr") + (A_PtrSize * 2), 0, "UPtr"), "Ptr", pStream)
Return hBitmap
}