; ##################################################################################
; # This #Include file was generated by Image2Include.ahk, you must not change it! #
; ##################################################################################
Create_advertiseCloseButton4_bmp(NewHandle := False) {
Static hBitmap := 0
If (NewHandle)
   hBitmap := 0
If (hBitmap)
   Return hBitmap
VarSetCapacity(B64, 1592 << !!A_IsUnicode)
B64 := "Qk2qBAAAAAAAADYAAAAoAAAAFAAAABMAAAABABgAAAAAAHQEAAAAAAAAAAAAAAAAAAAAAAAA////////////////////////GVxCGFxCGV1EGF5EGWBFGGBFGWNI////////////////////////////////////////////////////////GVxDGFxCGV9EGF5EGWFH////////////////////////////////////////////////////////////////GV1DGF1DGV9F////////////////////////////////////////////////////////////////////////GF1D////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////Gm5QGFhB////////////////////////////////////////////////////////////////////GmxOGWxPF1dBF1hA////////////////////////////////////////////////////////////GWlMGWxOGm5QGFlCF1hBGFpD////////////////////////////////////////////////////GmlNGWlMGmxPGW1PF1lCGFlDF1pCGFtD////////////////////////////////////////////GWZMGWhMGmpOGWtOGm1QGFpEF1pDGFpE////////////////////////////////////////////////////GWhNGWlNGWtPGWxPF1pDF1tE////////////////////////////////////////////////////////////GGpNGGtPGW1QGFxF////////////////////////////////////////////////////////////////////GWtPGGxP////////////////////////////////////////////////////////////////////////////GW1Q////////////////////////////////////////////////////////////////////////////////////////////////////////////////////FmFJ////////////////////////////////////////////////////////////////////////F2FKFmFJGGNL////////////////////////////////////////////////////////////////F2FKFmFJF2NKFmJKF2RL////////////////////////////////////////////////////////F2JKFmFKF2JLFmJKF2NLFmNKF2VM////////////////////////////"
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", 0, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
VarSetCapacity(Dec, DecLen, 0)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", &Dec, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
; Bitmap creation adopted from "How to convert Image data (JPEG/PNG/GIF) to hBITMAP?" by SKAN
; -> http://www.autohotkey.com/board/topic/21213-how-to-convert-image-data-jpegpnggif-to-hbitmap/?p=139257
hData := DllCall("Kernel32.dll\GlobalAlloc", "UInt", 2, "UPtr", DecLen, "UPtr")
pData := DllCall("Kernel32.dll\GlobalLock", "Ptr", hData, "UPtr")
DllCall("Kernel32.dll\RtlMoveMemory", "Ptr", pData, "Ptr", &Dec, "UPtr", DecLen)
DllCall("Kernel32.dll\GlobalUnlock", "Ptr", hData)
DllCall("Ole32.dll\CreateStreamOnHGlobal", "Ptr", hData, "Int", True, "PtrP", pStream)
hGdip := DllCall("Kernel32.dll\LoadLibrary", "Str", "Gdiplus.dll", "UPtr")
VarSetCapacity(SI, 16, 0), NumPut(1, SI, 0, "UChar")
DllCall("Gdiplus.dll\GdiplusStartup", "PtrP", pToken, "Ptr", &SI, "Ptr", 0)
DllCall("Gdiplus.dll\GdipCreateBitmapFromStream",  "Ptr", pStream, "PtrP", pBitmap)
DllCall("Gdiplus.dll\GdipCreateHBITMAPFromBitmap", "Ptr", pBitmap, "PtrP", hBitmap, "UInt", 0)
DllCall("Gdiplus.dll\GdipDisposeImage", "Ptr", pBitmap)
DllCall("Gdiplus.dll\GdiplusShutdown", "Ptr", pToken)
DllCall("Kernel32.dll\FreeLibrary", "Ptr", hGdip)
DllCall(NumGet(NumGet(pStream + 0, 0, "UPtr") + (A_PtrSize * 2), 0, "UPtr"), "Ptr", pStream)
Return hBitmap
}