; ##################################################################################
; # This #Include file was generated by Image2Include.ahk, you must not change it! #
; ##################################################################################
Create_thornUpgradeButton1_bmp(NewHandle := False) {
Static hBitmap := 0
If (NewHandle)
   hBitmap := 0
If (hBitmap)
   Return hBitmap
VarSetCapacity(B64, 1432 << !!A_IsUnicode)
B64 := "Qk0yBAAAAAAAADYAAAAoAAAAEwAAABEAAAABABgAAAAAAPwDAAAAAAAAAAAAAAAAAAAAAAAARJkzRZo0b7Fntdm1v+G/6fjp/////////////////v7+5e7lzdvNVlxKIiIROT4LgLMBgLMBc4kkAAAARJkzT6A/pdKhu927u927zuLO6PHo+vr6/////////////f39IyMBQlUAmbsAlMcAiLsAiLsAiLsAAAAARJkzcsBkstSyu927u927vte+w9TDy9vL6PLo+f/5+v/6IyMPdosLmbsA4vUA8v4E8P8C8P8C7v8AAAAARJkz5fLl2ezZvd69u927u927u927u927u927u927KisXYHUHm84I+/8B//wF++sC/OsA/u0A/OsAAAAAeq5x////////0+jTu927u927wePBu927u927rcurIiIRtMgD9P8G/PAF/eYA/+wE+egL/+4R//ATAAAAnrya////////3evdu927wePB2u3a1uzWv+G/NDgfa4sA8PoO/PIK/ewN/+8T/+4Y+OcgZmYiVV8YAAAAs9Wz/f/9/v/+6ffpvd+9wNnA4PHg/v7+8vnyIyMBqdwQ+/sC/u0Q4tUer6gis6YR3s0nZmYi////AAAAocOh6/br/v/+6ffpvd+9wNnA0+TT////////ICAP5PUY/uwQj48ZXGQmpbN5srKGXl4aW1sX+fn5AAAAocOhxtXG/v/+6ffpvd+9wNnA0+TT////////ICAP7/8S++YaWVkm////qqqDtbWQ9PTyXl4a+fn5AAAAoM+gvd+94vXi+v/6vd+9vd+9wuTC/Pz8////ICAP7/8S++YaaGgkaGgo2dnH+vr67e3rXl4a////AAAAoM+gu927zeXN9vz2vd+9vd+9v+G/9vb2+//7ICAP5OQY/+wZbGwX9vjyt7enfHxNiJRcTloi+fn5AAAAoc+hvN28vte+0OLQvd+9vd+9vd+9293by9/LLC8du8wA/f0Jg3ILsLea9vb29/f3k5pWVWYi////AAAArs+uzN3Mxd3Fvt2+vt2+vN28u927u927xNvEuMa2ISEP8voB5dQob3AdX18eWGAefoYhe4QjZmYiAAAAxuTGzN3Mxd3Fvt2+vt2+vN28u927v+G/3PPc9vr2ICAMsrwO/u4R/u0Q/+4R/+4i/Osf/Osf/+4iAAAAz+vPz97PxdzFvt2+vt2+vd28vd274Pfg////////////ICAPz88B8PgC++0A/OwF/+sI/+sG/+sJAAAA1uvW7u7uwtHBvt29vt28yN+92uvJ/f39/////////////Pz8Hx8OmaoB9f8p7v8A9PwN8vIA//8AAAAA1uvW+/v70+LSwd69wd68yeC99vvr////////////////////9PT0MDAgKisQanwPyNAC8/MBx9YDAAAA"
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", 0, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
VarSetCapacity(Dec, DecLen, 0)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", &Dec, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
; Bitmap creation adopted from "How to convert Image data (JPEG/PNG/GIF) to hBITMAP?" by SKAN
; -> http://www.autohotkey.com/board/topic/21213-how-to-convert-image-data-jpegpnggif-to-hbitmap/?p=139257
hData := DllCall("Kernel32.dll\GlobalAlloc", "UInt", 2, "UPtr", DecLen, "UPtr")
pData := DllCall("Kernel32.dll\GlobalLock", "Ptr", hData, "UPtr")
DllCall("Kernel32.dll\RtlMoveMemory", "Ptr", pData, "Ptr", &Dec, "UPtr", DecLen)
DllCall("Kernel32.dll\GlobalUnlock", "Ptr", hData)
DllCall("Ole32.dll\CreateStreamOnHGlobal", "Ptr", hData, "Int", True, "PtrP", pStream)
hGdip := DllCall("Kernel32.dll\LoadLibrary", "Str", "Gdiplus.dll", "UPtr")
VarSetCapacity(SI, 16, 0), NumPut(1, SI, 0, "UChar")
DllCall("Gdiplus.dll\GdiplusStartup", "PtrP", pToken, "Ptr", &SI, "Ptr", 0)
DllCall("Gdiplus.dll\GdipCreateBitmapFromStream",  "Ptr", pStream, "PtrP", pBitmap)
DllCall("Gdiplus.dll\GdipCreateHBITMAPFromBitmap", "Ptr", pBitmap, "PtrP", hBitmap, "UInt", 0)
DllCall("Gdiplus.dll\GdipDisposeImage", "Ptr", pBitmap)
DllCall("Gdiplus.dll\GdiplusShutdown", "Ptr", pToken)
DllCall("Kernel32.dll\FreeLibrary", "Ptr", hGdip)
DllCall(NumGet(NumGet(pStream + 0, 0, "UPtr") + (A_PtrSize * 2), 0, "UPtr"), "Ptr", pStream)
Return hBitmap
}