; ##################################################################################
; # This #Include file was generated by Image2Include.ahk, you must not change it! #
; ##################################################################################
Create_shieldUpgradeButton1_bmp(NewHandle := False) {
Static hBitmap := 0
If (NewHandle)
   hBitmap := 0
If (hBitmap)
   Return hBitmap
VarSetCapacity(B64, 1876 << !!A_IsUnicode)
B64 := "Qk1+BQAAAAAAADYAAAAoAAAAEQAAABoAAAABABgAAAAAAEgFAAAAAAAAAAAAAAAAAAAAAAAAHjY6F1t1Rr7wVM71O7fcKneFMHN+J15jFEtPFkZKTYWJesTIK1tsEUtfKWh9OIqcNoOTAFNeXhcmJxZuklrR8zqPnyJWVyxgYBpNTRdKSiVaWh5RUV6goJXI2VKGlxNGVw9NVhlYYACcoKAnNjYEExQ8mK0oe4siVVUZTEwgU1NekZlko6McT09NiIiZzN2WydplmKkvWGAXQUkAVmltECwzDisyCys7JVBhHUNQI1ZWaJuklsnZa6CuI1Zjcqi1mczdmczdl8nadpObUWJdABQ1PQssNAgpMQsxQhQ5SihNXWWYn5fK25nM3Y/D04K1xpfK25nM3YeyvScpGS0yC15jMAARJi4dPkYFJi42aHlYipt2qbqXytqZzN2ZzN2Yy9yXytuYy9xRZl4nKQmUswGQvwCJugIACEBPBB0lFTY4hb7Ilc7XlM7XltDYltDYltDYmczdmczdWHBtKysUlLQAmbsA6voE7/wFADN3iA4+RwgnJ5jS2pbQ2JbQ2JbQ2JbQ2JbQ2JnM3Ym1wSQlFYaqAebzBPX8Avr0AfvrAABWmqsrXmcFICCDvcWVz9eVz9eW0NiW0NiW0NiZzN04QTV3lwjh8Qn0/gb95gD/6wP/7QYAS56vLmNsDiAge73FlNHZltDYltDYl9DZl9HZmdvdIyMMttYU9PsK+uoG/+8S/+4V/+4YACd8jRZKUwobG3y+xpTR2ZbQ2JbQ2JfR2ZfR2X6UjTQ0E/n6A/r1BP3vFNTHG6SaDtXJIgAWa3wPQ0wSIyN8vsaU0dmW0NiW0NiX0dmj3eVQUUNxewf1/Qb25yRmZhtseTm+wI51dEIAL3OECDxFEjMzebO8lc/XltDYjtLSm97f7/v8SEg6gIoG+f4Kzr0fb29C9/j1Xl4q+Pj1AEaKmwg8RRY4OHy1vpXP15bQ2JDU1MXq6vj+/khIOoGLBvn+Ct3QL1tbGJqahOfn3v///wAbX3AIPEUcPj6IwcqVz9eW0Nio5OTm+Pj5//+IiH5gYAb7/wzXyyBte0z6+viNjVyyspUAFjlBEDI6GzxEmMvcmczdmczd0+7u/v//////8fHwJSUQ+voG5+IfVWYj+vr66+vo5OTiAAkqMgUhKR49RZnM3ZnM3azU3/r7+////////////yoqGM/SEPHyEamuL2dnKmFoKWBnKQADJCwMKTEzU1uZzN2ZzN3X7vD///////////////+rq6M3Nwby+QX56RL25hL25iD25iIABCY2AyU2X6nHlNfYs93e8vv7////////////////+/v6WVlKTEwL7+4B/fME/OwF/e0HADNogBg6S2Sx0JXZ2cTr6/z+/v////////////////////b29Ts7KDI0C/X+J/D+Bu/+AABjsM8VN0hPm7qX29vU9fX////////////////////////////z8/KkpJ0uLxJkcw6ltgQAPsPzJZC5NIiqtuLi/f7+////////////////////////////////2u/ut9fWkrCpXGpXAEzU/ky84il+oLHc3P///////////////////////////////////9jv78Di4rje5LTa3wBN1f9OvuQwhKehy8v////////////////////////////////8/PzR6OjA4uK64ee64ecAScH0NqzeI2J6rb29////////////////////////////////4ff3wOLpuODpuuHnuuHnADuy5TKp3Cdmfa68vP///////////////////////////////9fw8Lzf5bfg6brh57rh5wA="
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", 0, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
VarSetCapacity(Dec, DecLen, 0)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", &Dec, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
; Bitmap creation adopted from "How to convert Image data (JPEG/PNG/GIF) to hBITMAP?" by SKAN
; -> http://www.autohotkey.com/board/topic/21213-how-to-convert-image-data-jpegpnggif-to-hbitmap/?p=139257
hData := DllCall("Kernel32.dll\GlobalAlloc", "UInt", 2, "UPtr", DecLen, "UPtr")
pData := DllCall("Kernel32.dll\GlobalLock", "Ptr", hData, "UPtr")
DllCall("Kernel32.dll\RtlMoveMemory", "Ptr", pData, "Ptr", &Dec, "UPtr", DecLen)
DllCall("Kernel32.dll\GlobalUnlock", "Ptr", hData)
DllCall("Ole32.dll\CreateStreamOnHGlobal", "Ptr", hData, "Int", True, "PtrP", pStream)
hGdip := DllCall("Kernel32.dll\LoadLibrary", "Str", "Gdiplus.dll", "UPtr")
VarSetCapacity(SI, 16, 0), NumPut(1, SI, 0, "UChar")
DllCall("Gdiplus.dll\GdiplusStartup", "PtrP", pToken, "Ptr", &SI, "Ptr", 0)
DllCall("Gdiplus.dll\GdipCreateBitmapFromStream",  "Ptr", pStream, "PtrP", pBitmap)
DllCall("Gdiplus.dll\GdipCreateHBITMAPFromBitmap", "Ptr", pBitmap, "PtrP", hBitmap, "UInt", 0)
DllCall("Gdiplus.dll\GdipDisposeImage", "Ptr", pBitmap)
DllCall("Gdiplus.dll\GdiplusShutdown", "Ptr", pToken)
DllCall("Kernel32.dll\FreeLibrary", "Ptr", hGdip)
DllCall(NumGet(NumGet(pStream + 0, 0, "UPtr") + (A_PtrSize * 2), 0, "UPtr"), "Ptr", pStream)
Return hBitmap
}