; ##################################################################################
; # This #Include file was generated by Image2Include.ahk, you must not change it! #
; ##################################################################################
Create_steelUpgradeButton1_bmp(NewHandle := False) {
Static hBitmap := 0
If (NewHandle)
   hBitmap := 0
If (hBitmap)
   Return hBitmap
VarSetCapacity(B64, 1640 << !!A_IsUnicode)
B64 := "Qk3OBAAAAAAAADYAAAAoAAAAEgAAABUAAAABABgAAAAAAJgEAAAAAAAAAAAAAAAAAAAAAAAAh4eHtra22dnZ2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjYZWVWIyMBmboAlcUAi74AiLsAiLsAAACWlpbQ0NDZ2dnY2NjY2NjY2NjY2NjY2NjY2NjY2NhxcWYpKRGZuwCZuwDu/ATz/wXw/wLu/wAAALGxsdnZ2dnZ2djY2NjY2NjY2NjY2NjY2NjY2L+/vCIiEYqwAOn2BPn/Avv0AfvqAP3sAP3tAQAAx8fH29vb2tra2NjY2NjY2NjY2NjY2NjY2NjYOzsse50I5fQJ9f4G/eUA/+sD/+0G/OsO/u4RAADPz8/b29va2trY2NjY2NjY2NjY2NjY2NjY2NgiIgq52RX1+wr66Qb/7xP/7hb/7hnm1xNVXxgAANbW1tra2tra2tjY2NjY2NjY2NjY2NjY2IeHgDU1E/z8Avr1BP3vFdLFG6CWDtPHIqCZKbW1mAAA2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NjYRkY5dH4G9f0G9uYmX18bZ3U7wMKUcHBEW1sXvLypAADY2NjY2NjY2NjY2NjY2NjY2NjY2NjY2NhBQTOBiwb5/grMux9wcET///9ZWST///+Dg1W8vKkAANjY2NjY2NjY2NjY2Nvb29vb29nZ2dra2kFBNIGLBvn+Ct7RMFpaFpWVfe/v6P///25uQL+/qwAA2NjY2NjY2NjY19fX7+/v9vb27e3t39/fenpxXl4G+/8M18sfbn1P////iIhVrq6PTloivLypAADY2NjY2NjY2Nje3t78/Pz////////////q6ukiIhH6+gbo4x9UZSH6+vrw8PDn5+dVZiK1tZsAANnZ2dnZ2dzc3PPz8/////////////////7+/ioqGM3QEfLzEK6yMF9fHllgHlhgHry0NmZmIgAA2tra2tra5OTk/f39////////////////////srKrLi4F8vkE/ewQ/+4R/+4g/+4i/Osf/+4iAADa2tra2trz8/P///////////////////////////9bW05CQgvu7gD98wP87AT97QX/6wf/6wkAANnZ2dnZ2eXl5fb29v7+/v///////////////////////zs7KicpDPX/Ke//Bu7/APP2Bv//AAAA2NjY2NjY2dnZ4eHh9PT0////////////////////////////rKymIiIRW2oPobIE6u0B7vUJAADY2NjY2NjY2NjZ2dnZ2dnv7+/+/v7////////////////////////////Ly8ZxcWUxMR4wMB0AANjY2NjY2NjY2NjY2NjY2Nzc3O3t7f39/f///////////////////////////////////////wAA2NjY2NjY2NjY2NjY2NjY2dnZ3Nzc5eXl/f39////////////////////////////////////AADY2NjY2NjY2NjY2NjY2NjZ2dnb29vh4eH9/f3///////////////////////////////////8AANjY2NjY2NjY2NjY2NjY2NnZ2dvb2+jo6P///////////////////////////////////////wAA"
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", 0, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
VarSetCapacity(Dec, DecLen, 0)
If !DllCall("Crypt32.dll\CryptStringToBinary", "Ptr", &B64, "UInt", 0, "UInt", 0x01, "Ptr", &Dec, "UIntP", DecLen, "Ptr", 0, "Ptr", 0)
   Return False
; Bitmap creation adopted from "How to convert Image data (JPEG/PNG/GIF) to hBITMAP?" by SKAN
; -> http://www.autohotkey.com/board/topic/21213-how-to-convert-image-data-jpegpnggif-to-hbitmap/?p=139257
hData := DllCall("Kernel32.dll\GlobalAlloc", "UInt", 2, "UPtr", DecLen, "UPtr")
pData := DllCall("Kernel32.dll\GlobalLock", "Ptr", hData, "UPtr")
DllCall("Kernel32.dll\RtlMoveMemory", "Ptr", pData, "Ptr", &Dec, "UPtr", DecLen)
DllCall("Kernel32.dll\GlobalUnlock", "Ptr", hData)
DllCall("Ole32.dll\CreateStreamOnHGlobal", "Ptr", hData, "Int", True, "PtrP", pStream)
hGdip := DllCall("Kernel32.dll\LoadLibrary", "Str", "Gdiplus.dll", "UPtr")
VarSetCapacity(SI, 16, 0), NumPut(1, SI, 0, "UChar")
DllCall("Gdiplus.dll\GdiplusStartup", "PtrP", pToken, "Ptr", &SI, "Ptr", 0)
DllCall("Gdiplus.dll\GdipCreateBitmapFromStream",  "Ptr", pStream, "PtrP", pBitmap)
DllCall("Gdiplus.dll\GdipCreateHBITMAPFromBitmap", "Ptr", pBitmap, "PtrP", hBitmap, "UInt", 0)
DllCall("Gdiplus.dll\GdipDisposeImage", "Ptr", pBitmap)
DllCall("Gdiplus.dll\GdiplusShutdown", "Ptr", pToken)
DllCall("Kernel32.dll\FreeLibrary", "Ptr", hGdip)
DllCall(NumGet(NumGet(pStream + 0, 0, "UPtr") + (A_PtrSize * 2), 0, "UPtr"), "Ptr", pStream)
Return hBitmap
}